// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hdsvm_cd_cpp
List hdsvm_cd_cpp(double alpha, double lam2, double hval, int nobs, int nvars, NumericMatrix X, NumericVector y, IntegerVector jd, int pfncol, NumericMatrix pf, NumericVector pf2, int dfmax, int pmax, int nlam, double flmin, NumericVector ulam, double eps, int isd, int maxit, double sigma, int is_exact);
RcppExport SEXP _hdstats_hdsvm_cd_cpp(SEXP alphaSEXP, SEXP lam2SEXP, SEXP hvalSEXP, SEXP nobsSEXP, SEXP nvarsSEXP, SEXP XSEXP, SEXP ySEXP, SEXP jdSEXP, SEXP pfncolSEXP, SEXP pfSEXP, SEXP pf2SEXP, SEXP dfmaxSEXP, SEXP pmaxSEXP, SEXP nlamSEXP, SEXP flminSEXP, SEXP ulamSEXP, SEXP epsSEXP, SEXP isdSEXP, SEXP maxitSEXP, SEXP sigmaSEXP, SEXP is_exactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< double >::type hval(hvalSEXP);
    Rcpp::traits::input_parameter< int >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< int >::type nvars(nvarsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type jd(jdSEXP);
    Rcpp::traits::input_parameter< int >::type pfncol(pfncolSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf(pfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pf2(pf2SEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    Rcpp::traits::input_parameter< int >::type nlam(nlamSEXP);
    Rcpp::traits::input_parameter< double >::type flmin(flminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ulam(ulamSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type isd(isdSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type is_exact(is_exactSEXP);
    rcpp_result_gen = Rcpp::wrap(hdsvm_cd_cpp(alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact));
    return rcpp_result_gen;
END_RCPP
}
// huber_path_cpp
List huber_path_cpp(double alpha, double lam2, double hval, NumericVector maj, double mval, NumericMatrix X, NumericVector y, IntegerVector ju, int pfncol, NumericMatrix pf, NumericVector pf2, int dfmax, int pmax, int nlam, double flmin, NumericVector ulam, double eps, int maxit, int istrong);
RcppExport SEXP _hdstats_huber_path_cpp(SEXP alphaSEXP, SEXP lam2SEXP, SEXP hvalSEXP, SEXP majSEXP, SEXP mvalSEXP, SEXP XSEXP, SEXP ySEXP, SEXP juSEXP, SEXP pfncolSEXP, SEXP pfSEXP, SEXP pf2SEXP, SEXP dfmaxSEXP, SEXP pmaxSEXP, SEXP nlamSEXP, SEXP flminSEXP, SEXP ulamSEXP, SEXP epsSEXP, SEXP maxitSEXP, SEXP istrongSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< double >::type hval(hvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maj(majSEXP);
    Rcpp::traits::input_parameter< double >::type mval(mvalSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ju(juSEXP);
    Rcpp::traits::input_parameter< int >::type pfncol(pfncolSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf(pfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pf2(pf2SEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    Rcpp::traits::input_parameter< int >::type nlam(nlamSEXP);
    Rcpp::traits::input_parameter< double >::type flmin(flminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ulam(ulamSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type istrong(istrongSEXP);
    rcpp_result_gen = Rcpp::wrap(huber_path_cpp(alpha, lam2, hval, maj, mval, X, y, ju, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, maxit, istrong));
    return rcpp_result_gen;
END_RCPP
}
// huber_cd_cpp
List huber_cd_cpp(double alpha, double lam2, double hval, int nobs, int nvars, NumericMatrix X, NumericVector y, IntegerVector jd, int pfncol, NumericMatrix pf, NumericVector pf2, int dfmax, int pmax, int nlam, double flmin, NumericVector ulam, double eps, int isd, int maxit, int istrong);
RcppExport SEXP _hdstats_huber_cd_cpp(SEXP alphaSEXP, SEXP lam2SEXP, SEXP hvalSEXP, SEXP nobsSEXP, SEXP nvarsSEXP, SEXP XSEXP, SEXP ySEXP, SEXP jdSEXP, SEXP pfncolSEXP, SEXP pfSEXP, SEXP pf2SEXP, SEXP dfmaxSEXP, SEXP pmaxSEXP, SEXP nlamSEXP, SEXP flminSEXP, SEXP ulamSEXP, SEXP epsSEXP, SEXP isdSEXP, SEXP maxitSEXP, SEXP istrongSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< double >::type hval(hvalSEXP);
    Rcpp::traits::input_parameter< int >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< int >::type nvars(nvarsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type jd(jdSEXP);
    Rcpp::traits::input_parameter< int >::type pfncol(pfncolSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf(pfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pf2(pf2SEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    Rcpp::traits::input_parameter< int >::type nlam(nlamSEXP);
    Rcpp::traits::input_parameter< double >::type flmin(flminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ulam(ulamSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type isd(isdSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type istrong(istrongSEXP);
    rcpp_result_gen = Rcpp::wrap(huber_cd_cpp(alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, istrong));
    return rcpp_result_gen;
END_RCPP
}
// huber_drv_cpp
NumericVector huber_drv_cpp(const NumericMatrix& X, const NumericVector& r, const double hval);
RcppExport SEXP _hdstats_huber_drv_cpp(SEXP XSEXP, SEXP rSEXP, SEXP hvalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type hval(hvalSEXP);
    rcpp_result_gen = Rcpp::wrap(huber_drv_cpp(X, r, hval));
    return rcpp_result_gen;
END_RCPP
}
// lqr_hd_cpp
List lqr_hd_cpp(double alpha, double lam2, double hval, int nobs, int nvars, NumericMatrix X, NumericVector y, double tau, IntegerVector jd, int pfncol, NumericMatrix pf, NumericVector pf2, int dfmax, int pmax, int nlam, double flmin, NumericVector ulam, double eps, int isd, int maxit, double sigma, int is_exact);
RcppExport SEXP _hdstats_lqr_hd_cpp(SEXP alphaSEXP, SEXP lam2SEXP, SEXP hvalSEXP, SEXP nobsSEXP, SEXP nvarsSEXP, SEXP XSEXP, SEXP ySEXP, SEXP tauSEXP, SEXP jdSEXP, SEXP pfncolSEXP, SEXP pfSEXP, SEXP pf2SEXP, SEXP dfmaxSEXP, SEXP pmaxSEXP, SEXP nlamSEXP, SEXP flminSEXP, SEXP ulamSEXP, SEXP epsSEXP, SEXP isdSEXP, SEXP maxitSEXP, SEXP sigmaSEXP, SEXP is_exactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< double >::type hval(hvalSEXP);
    Rcpp::traits::input_parameter< int >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< int >::type nvars(nvarsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type jd(jdSEXP);
    Rcpp::traits::input_parameter< int >::type pfncol(pfncolSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pf(pfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pf2(pf2SEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    Rcpp::traits::input_parameter< int >::type nlam(nlamSEXP);
    Rcpp::traits::input_parameter< double >::type flmin(flminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ulam(ulamSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type isd(isdSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type is_exact(is_exactSEXP);
    rcpp_result_gen = Rcpp::wrap(lqr_hd_cpp(alpha, lam2, hval, nobs, nvars, X, y, tau, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hdstats_hdsvm_cd_cpp", (DL_FUNC) &_hdstats_hdsvm_cd_cpp, 21},
    {"_hdstats_huber_path_cpp", (DL_FUNC) &_hdstats_huber_path_cpp, 19},
    {"_hdstats_huber_cd_cpp", (DL_FUNC) &_hdstats_huber_cd_cpp, 20},
    {"_hdstats_huber_drv_cpp", (DL_FUNC) &_hdstats_huber_drv_cpp, 3},
    {"_hdstats_lqr_hd_cpp", (DL_FUNC) &_hdstats_lqr_hd_cpp, 22},
    {NULL, NULL, 0}
};

RcppExport void R_init_hdstats(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
