# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hdsvm_cd_cpp <- function(alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact) {
    .Call(`_hdstats_hdsvm_cd_cpp`, alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact)
}

huber_cd_cpp <- function(alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, istrong) {
    .Call(`_hdstats_huber_cd_cpp`, alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, istrong)
}

lqr_hd_cpp <- function(alpha, lam2, hval, nobs, nvars, X, y, tau, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact) {
    .Call(`_hdstats_lqr_hd_cpp`, alpha, lam2, hval, nobs, nvars, X, y, tau, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact)
}

