# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hdsvm_cd_cpp <- function(alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact) {
    .Call(`_hdststs_hdsvm_cd_cpp`, alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact)
}

huber_path_cpp <- function(alpha, lam2, hval, maj, mval, X, y, ju, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, maxit, istrong) {
    .Call(`_hdststs_huber_path_cpp`, alpha, lam2, hval, maj, mval, X, y, ju, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, maxit, istrong)
}

huber_cd_cpp <- function(alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, istrong) {
    .Call(`_hdststs_huber_cd_cpp`, alpha, lam2, hval, nobs, nvars, X, y, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, istrong)
}

huber_drv_cpp <- function(X, r, hval) {
    .Call(`_hdststs_huber_drv_cpp`, X, r, hval)
}

lqr_hd_cpp <- function(alpha, lam2, hval, nobs, nvars, X, y, tau, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact) {
    .Call(`_hdststs_lqr_hd_cpp`, alpha, lam2, hval, nobs, nvars, X, y, tau, jd, pfncol, pf, pf2, dfmax, pmax, nlam, flmin, ulam, eps, isd, maxit, sigma, is_exact)
}

